import { it, expect, vi } from 'vitest'
import userEvent from '@testing-library/user-event'
import { render, screen } from '../../../test-utils'
import { RuntimeRolePrompts } from '../RuntimeRolePrompts'
const defaults = { architect: 'Plan the change', developer: 'Implement the change', reviewer: 'Review the change' }
const response = (overrides = {}) => ({ ok: true, json: async () => ({ defaults, overrides }) })
it('keeps edits between roles, saves overrides and resets just one role', async () => {
  const user = userEvent.setup()
  global.fetch = vi.fn().mockResolvedValueOnce(response())
    .mockResolvedValueOnce(response({ architect: 'My plan', developer: 'My implementation' }))
    .mockResolvedValueOnce(response({ developer: 'My implementation' }))
  render(<RuntimeRolePrompts />)
  const field = await screen.findByRole('textbox')
  expect(field).toHaveValue(defaults.architect)
  await user.clear(field); await user.type(field, 'My plan')
  await user.click(screen.getByRole('tab', { name: 'Developer' }))
  await user.clear(screen.getByRole('textbox')); await user.type(screen.getByRole('textbox'), 'My implementation')
  await user.click(screen.getByRole('tab', { name: 'Architect' }))
  expect(screen.getByRole('textbox')).toHaveValue('My plan')
  await user.click(screen.getByRole('button', { name: 'Save prompts' }))
  await screen.findByText('Role prompts saved')
  expect(JSON.parse(vi.mocked(fetch).mock.calls[1][1]!.body as string)).toEqual({ overrides: { architect: 'My plan', developer: 'My implementation' } })
  await user.click(screen.getByRole('button', { name: 'Restore default' }))
  expect(screen.getByRole('textbox')).toHaveValue(defaults.architect)
  await user.click(screen.getByRole('button', { name: 'Save prompts' }))
  await screen.findByText('Role prompts saved')
  expect(JSON.parse(vi.mocked(fetch).mock.calls[2][1]!.body as string)).toEqual({ overrides: { developer: 'My implementation' } })
})
it('blocks blank definitions, retains rejected edits and can discard them', async () => {
  const user = userEvent.setup()
  global.fetch = vi.fn().mockResolvedValueOnce(response()).mockResolvedValueOnce({ ok: false, json: async () => ({ message: 'Disk unavailable' }) })
  render(<RuntimeRolePrompts />)
  const field = await screen.findByRole('textbox')
  await user.clear(field)
  expect(screen.getByRole('button', { name: 'Save prompts' })).toBeDisabled()
  await user.type(field, 'Keep this draft')
  await user.click(screen.getByRole('button', { name: 'Save prompts' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Disk unavailable')
  expect(field).toHaveValue('Keep this draft')
  await user.click(screen.getByRole('button', { name: 'Discard changes' }))
  expect(field).toHaveValue(defaults.architect)
})
it('allows retrying a failed catalog load', async () => {
  const user = userEvent.setup()
  global.fetch = vi.fn().mockRejectedValueOnce(new Error('Core unavailable')).mockResolvedValueOnce(response())
  render(<RuntimeRolePrompts />)
  expect(await screen.findByRole('alert')).toHaveTextContent('Core unavailable')
  await user.click(screen.getByRole('button', { name: 'Retry' }))
  expect(await screen.findByRole('textbox')).toHaveValue(defaults.architect)
})
