import { beforeEach, expect, it, vi } from 'vitest'
import userEvent from '@testing-library/user-event'
import { act, render, screen, waitFor } from '../../../../test-utils'
import { RuntimeRetention } from '../RuntimeRetention'
const response = (value: unknown, ok = true) => ({ ok, json: async () => value }) as Response
const preview = { dryRun: true, runs: [{ runId: 'old-run', state: 'eligible', reasons: [] }, { runId: 'active-run', state: 'protected', reasons: ['active'] }], packages: ['digest'], errors: [] }
beforeEach(() => { vi.clearAllMocks(); global.fetch = vi.fn() })
it('loads only when opened and requires an explicit preview before deleting history', async () => {
  const user = userEvent.setup(), changed = vi.fn()
  vi.mocked(fetch).mockResolvedValueOnce(response({ policy: { days: 30 } })).mockResolvedValueOnce(response(preview)).mockResolvedValueOnce(response({ ...preview, dryRun: false, runs: [{ runId: 'old-run', state: 'expired', reasons: [] }] }))
  render(<RuntimeRetention projectId="p1" onChanged={changed} />)
  expect(fetch).not.toHaveBeenCalled()
  await user.click(screen.getByText('History retention'))
  await waitFor(() => expect(screen.getByLabelText('Retention days')).toHaveValue(30))
  expect(screen.queryByRole('button', { name: 'Delete expired history' })).not.toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: 'Preview cleanup' }))
  expect(await screen.findByText(/Eligible: 1 histories and 1 unused Core versions/)).toBeInTheDocument()
  expect(screen.getByText(/Active execution/)).toBeInTheDocument()
  expect(fetch).toHaveBeenLastCalledWith('/api/projects/p1/agent-runtime/retention/collect', expect.objectContaining({ body: '{"dryRun":true}' }))
  await user.click(screen.getByRole('button', { name: 'Delete expired history' }))
  await waitFor(() => expect(changed).toHaveBeenCalledOnce())
  expect(fetch).toHaveBeenLastCalledWith('/api/projects/p1/agent-runtime/retention/collect', expect.objectContaining({ body: '{"dryRun":false}' }))
  expect(screen.queryByRole('button', { name: 'Delete expired history' })).not.toBeInTheDocument()
})
it('keeps indefinite retention until a valid project policy is explicitly saved', async () => {
  const user = userEvent.setup()
  vi.mocked(fetch).mockResolvedValueOnce(response({ policy: { days: null } })).mockResolvedValueOnce(response({ policy: { days: 90 } }))
  render(<RuntimeRetention projectId="p1" onChanged={() => {}} />)
  await user.click(screen.getByText('History retention'))
  const forever = await screen.findByRole('checkbox', { name: 'Keep history indefinitely' })
  await waitFor(() => expect(forever).toBeEnabled())
  expect(forever).toBeChecked(); expect(screen.getByRole('button', { name: 'Preview cleanup' })).toBeDisabled()
  await user.click(forever)
  expect(screen.getByRole('button', { name: 'Preview cleanup' })).toBeDisabled()
  await user.click(screen.getByRole('button', { name: 'Save retention' }))
  await waitFor(() => expect(screen.getByRole('button', { name: 'Preview cleanup' })).toBeEnabled())
  expect(fetch).toHaveBeenLastCalledWith('/api/projects/p1/agent-runtime/retention', expect.objectContaining({ method: 'PUT', body: '{"days":90}' }))
  const days = screen.getByLabelText('Retention days'); await user.clear(days); await user.type(days, '0')
  expect(screen.getByRole('button', { name: 'Save retention' })).toBeDisabled()
})
it('does not apply a delayed policy response to a different selected project', async () => {
  const user = userEvent.setup(); let resolve!: (value: Response) => void
  vi.mocked(fetch).mockImplementationOnce(() => new Promise(done => { resolve = done })).mockResolvedValueOnce(response({ policy: { days: 365 } }))
  const view = render(<RuntimeRetention projectId="p1" onChanged={() => {}} />)
  await user.click(screen.getByText('History retention')); await waitFor(() => expect(fetch).toHaveBeenCalledOnce())
  view.rerender(<RuntimeRetention projectId="p2" onChanged={() => {}} />)
  await user.click(screen.getByText('History retention'))
  await waitFor(() => expect(screen.getByLabelText('Retention days')).toHaveValue(365))
  await act(async () => { resolve(response({ policy: { days: 1 } })) })
  expect(screen.getByLabelText('Retention days')).toHaveValue(365)
})
it('reports unavailable inspection without offering deletion', async () => {
  const user = userEvent.setup()
  vi.mocked(fetch).mockResolvedValueOnce(response({ policy: { days: 30 } })).mockResolvedValueOnce(response({ message: 'Original runtime unavailable' }, false))
  render(<RuntimeRetention projectId="p1" onChanged={() => {}} />)
  await user.click(screen.getByText('History retention')); await waitFor(() => expect(screen.getByRole('button', { name: 'Preview cleanup' })).toBeEnabled())
  await user.click(screen.getByRole('button', { name: 'Preview cleanup' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Original runtime unavailable')
  expect(screen.queryByRole('button', { name: 'Delete expired history' })).not.toBeInTheDocument()
})
it('drops an earlier eligible preview when a later preview or deletion fails', async () => {
  const user = userEvent.setup()
  vi.mocked(fetch).mockResolvedValueOnce(response({ policy: { days: 30 } })).mockResolvedValueOnce(response(preview))
    .mockResolvedValueOnce(response({ message: 'Core status unavailable' }, false))
    .mockResolvedValueOnce(response(preview)).mockResolvedValueOnce(response({ message: 'Retention busy' }, false))
  render(<RuntimeRetention projectId="p1" onChanged={() => {}} />)
  await user.click(screen.getByText('History retention')); await waitFor(() => expect(screen.getByRole('button', { name: 'Preview cleanup' })).toBeEnabled())
  await user.click(screen.getByRole('button', { name: 'Preview cleanup' }))
  expect(await screen.findByRole('button', { name: 'Delete expired history' })).toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: 'Preview cleanup' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Core status unavailable')
  expect(screen.queryByRole('button', { name: 'Delete expired history' })).not.toBeInTheDocument()
  expect(screen.queryByText(/Eligible:/)).not.toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: 'Preview cleanup' }))
  await user.click(await screen.findByRole('button', { name: 'Delete expired history' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Retention busy')
  expect(screen.queryByRole('button', { name: 'Delete expired history' })).not.toBeInTheDocument()
})
