import fs from 'fs'
import os from 'os'
import path from 'path'

import { getBundledOpenspecCli } from './bundled-openspec'
import { resolveBundledNodeExe } from './path-resolver'

/**
 * openspec PATH shim — the robustness backstop for relocated Claude rails.
 *
 * THE PROBLEM. When a project's artifacts are RELOCATED to the home workspace,
 * the rail's `claude` child is spawned with `cwd = <workspace>`. The repo's
 * `openspec/` tree (changes, specs, .git) lives in the REPO, not the workspace.
 * specrails-core's stage-3 templates wrap repo-resident `openspec <verb>` calls
 * in `(cd "${SPECRAILS_REPO_DIR:-.}" && openspec …)` so they land in the repo —
 * but a BARE `openspec …` that a skill, sub-agent, or an un-wrapped template
 * line emits would run from the workspace cwd, where there is no OpenSpec
 * project → "Error: not an OpenSpec project".
 *
 * THE FIX. For a relocated rail we materialize a per-job shim directory and
 * PREPEND it to the spawn `PATH`. It contains an `openspec` executable (POSIX
 * `sh` script + a Windows `openspec.cmd`) that unconditionally does:
 *
 *     cd "$SPECRAILS_REPO_DIR" && exec <real openspec> "$@"
 *
 * so EVERY `openspec` invocation — wrapped OR bare, skill- OR template-driven —
 * resolves against the repo. The "real openspec" is the bundled openspec
 * (`node <cli>`) when present, else the legacy `npx @fission-ai/openspec@<pin>`.
 *
 * EXISTENCE-GATED. Only injected for a RELOCATED rail. Legacy (in-repo) rails
 * spawn from the repo cwd where a bare `openspec` already resolves correctly, so
 * the shim is never created and `PATH` is byte-identical to today.
 */

/** Pinned openspec npm spec for the `npx` fallback when no bundled openspec is
 *  present. Matches specrails-core's `pinned-versions.json` openspec pin and the
 *  desktop OPENSPEC_BUNDLE_VERSION in the release workflow. */
export const OPENSPEC_NPX_SPEC = '@fission-ai/openspec@1.4.1'

/** `~/.specrails/projects/<slug>/openspec-shim/<jobId>` — the per-job shim dir. */
export function openspecShimDir(slug: string, jobId: string, home: string = os.homedir()): string {
  return path.join(home, '.specrails', 'projects', slug, 'openspec-shim', jobId)
}

/**
 * Build the command the shim should `exec` to run the REAL openspec, as an argv
 * array already shell-quoted into a single string. Prefers the bundled openspec
 * (`node <cli>`); falls back to `npx -y <pinned openspec>`.
 */
function realOpenspecInvocation(): { posix: string; windows: string } {
  const cli = getBundledOpenspecCli()
  if (cli) {
    // <node> "<cli>" — invoke the bundled openspec as a node script (Tauri strips
    // exec bits from bundled resources, so it can't be run as a binary). Anchor to
    // the absolute bundled node when present rather than a bare `node` (which is
    // PATH-dependent and may be absent / a mismatched system node in a partial
    // bundle); fall back to bare `node` only when no bundled runtimes ship.
    const node = resolveBundledNodeExe()
    return {
      posix: `${node ? shq(node) : 'node'} ${shq(cli)}`,
      windows: `${node ? winq(node) : 'node'} ${winq(cli)}`,
    }
  }
  // Legacy fallback: npx resolves + caches openspec. `-y` skips the install
  // confirmation prompt (rails are headless).
  return {
    posix: `npx -y ${shq(OPENSPEC_NPX_SPEC)}`,
    windows: `npx -y ${winq(OPENSPEC_NPX_SPEC)}`,
  }
}

/** POSIX single-quote a string for embedding in an `sh` script. */
function shq(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`
}

/** Windows double-quote a string for a `.cmd` script. */
function winq(s: string): string {
  return `"${s.replace(/"/g, '""')}"`
}

/**
 * Materialize the per-job openspec shim directory and return its absolute path
 * (to be PREPENDED to the spawn PATH). Writes both an `openspec` POSIX script
 * (chmod 755 inside a 700 dir) and an `openspec.cmd` for Windows. The shim cd's
 * into `$SPECRAILS_REPO_DIR` (defaulting to `.` so a missing var degrades to the
 * cwd) before exec'ing the real openspec, so the repo's OpenSpec project is
 * always the one operated on.
 *
 * Returns null when the shim could not be created (best-effort — a failure must
 * never block a spawn; the rail still runs, just without the shim's safety net).
 */
export function ensureOpenspecShim(
  slug: string,
  jobId: string,
  home: string = os.homedir(),
): string | null {
  try {
    const dir = openspecShimDir(slug, jobId, home)
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 })
    try {
      fs.chmodSync(dir, 0o700)
    } catch {
      /* chmod may be unsupported (Windows) — non-fatal */
    }
    const { posix, windows } = realOpenspecInvocation()

    // POSIX shim: `openspec` (no extension). `${SPECRAILS_REPO_DIR:-.}` makes a
    // missing var degrade to the current dir instead of an unbound-var error.
    const posixScript =
      '#!/bin/sh\n' +
      '# Auto-generated by specrails-desktop (relocated-rail openspec shim).\n' +
      '# Re-points every bare `openspec` call at the repo working tree.\n' +
      'cd "${SPECRAILS_REPO_DIR:-.}" || exit 1\n' +
      `exec ${posix} "$@"\n`
    const posixPath = path.join(dir, 'openspec')
    fs.writeFileSync(posixPath, posixScript, { mode: 0o755 })
    try {
      fs.chmodSync(posixPath, 0o755)
    } catch {
      /* non-fatal */
    }

    // Windows shim: `openspec.cmd`. cmd.exe resolves `openspec` to this on PATH.
    const winScript =
      '@echo off\r\n' +
      'rem Auto-generated by specrails-desktop (relocated-rail openspec shim).\r\n' +
      'if defined SPECRAILS_REPO_DIR cd /d "%SPECRAILS_REPO_DIR%"\r\n' +
      `${windows} %*\r\n`
    fs.writeFileSync(path.join(dir, 'openspec.cmd'), winScript)

    return dir
  } catch {
    return null
  }
}

/**
 * Prepend `shimDir` to a PATH string using the platform delimiter, de-duping a
 * leading entry that already equals `shimDir`. Returns the original `pathValue`
 * unchanged when `shimDir` is null/empty.
 */
export function prependShimToPath(pathValue: string | undefined, shimDir: string | null): string {
  const base = pathValue ?? ''
  if (!shimDir) return base
  const sep = path.delimiter
  const segments = base.split(sep).filter((s) => s.length > 0)
  if (segments[0] === shimDir) return base
  return [shimDir, ...segments].join(sep)
}

/** Remove a per-job shim dir (best-effort cleanup). No-op when absent. */
export function removeOpenspecShim(slug: string, jobId: string, home: string = os.homedir()): void {
  try {
    const dir = openspecShimDir(slug, jobId, home)
    if (fs.existsSync(dir)) fs.rmSync(dir, { recursive: true, force: true })
  } catch {
    /* best-effort */
  }
}
