import * as fs from 'fs'
import * as path from 'path'
import * as crypto from 'crypto'
import { resolveHome } from './artifact-registry'

/**
 * Deterministic repository map — pure filesystem inspection, zero AI cost.
 *
 * Generated at spawn time and handed to pipeline spawns via
 * `SPECRAILS_REPO_MAP_PATH`, so the expensive exploration phase starts with
 * the repo's shape (packages, ecosystems, rough sizes) already in context
 * instead of burning its first turns on `ls`/`find`/README discovery — every
 * one of those turns re-bills the whole accumulated context.
 *
 * Kill switch: `SPECRAILS_REPO_MAP=false` (exact string) disables injection.
 */

export interface RepoMapService {
  /** Repo-relative dir, '' for the root package. */
  dir: string
  name: string
  ecosystem: string
  sizeBucket: 'small' | 'medium' | 'large'
  hasReadme: boolean
}

export interface RepoMap {
  readmeExcerpt: string | null
  services: RepoMapService[]
  truncated: boolean
}

const SKIP_DIRS = new Set([
  'node_modules', 'vendor', 'dist', 'build', 'out', 'coverage', 'target',
  '__pycache__', 'venv', '.venv', 'Pods', 'DerivedData',
])

/** Manifest filename → ecosystem label. First match wins (iteration order). */
const MANIFESTS: ReadonlyArray<[string, string]> = [
  ['package.json', 'node'],
  ['pyproject.toml', 'python'],
  ['setup.py', 'python'],
  ['requirements.txt', 'python'],
  ['go.mod', 'go'],
  ['Cargo.toml', 'rust'],
  ['pom.xml', 'jvm'],
  ['build.gradle', 'jvm'],
  ['build.gradle.kts', 'jvm'],
  ['Package.swift', 'swift'],
  ['Gemfile', 'ruby'],
  ['composer.json', 'php'],
]

const MAX_SERVICES = 40
const README_MAX_LINES = 12
const README_MAX_CHARS = 800
/** File-count scan caps — the bucket is a rough size label, not a census. */
const SCAN_MAX_DEPTH = 2
const SCAN_MAX_ENTRIES = 500

export function buildRepoMap(repoDir: string): RepoMap {
  const services: RepoMapService[] = []
  const seen = new Set<string>()

  const addService = (relDir: string): void => {
    if (seen.has(relDir) || services.length >= MAX_SERVICES + 1) return
    const abs = relDir === '' ? repoDir : path.join(repoDir, relDir)
    const eco = detectEcosystem(abs)
    if (!eco) return
    seen.add(relDir)
    services.push({
      dir: relDir,
      name: packageName(abs) ?? (relDir === '' ? path.basename(repoDir) : path.basename(relDir)),
      ecosystem: eco,
      sizeBucket: sizeBucket(abs),
      hasReadme: readmePath(abs) !== null,
    })
  }

  addService('')
  for (const entry of listDirs(repoDir)) {
    addService(entry)
  }
  // npm/yarn workspaces can nest packages one level below the top-level scan.
  for (const rel of resolveNpmWorkspaces(repoDir)) {
    addService(rel)
  }

  const truncated = services.length > MAX_SERVICES
  return {
    readmeExcerpt: readReadmeExcerpt(repoDir),
    services: services.slice(0, MAX_SERVICES),
    truncated,
  }
}

export function formatRepoMap(map: RepoMap): string {
  const lines: string[] = ['# Repository map (deterministic — generated by Specrails, no AI)', '']
  if (map.readmeExcerpt) {
    lines.push('## README excerpt', '', map.readmeExcerpt, '')
  }
  lines.push('## Packages')
  if (map.services.length === 0) {
    lines.push('- (no recognized package manifests found)')
  }
  for (const s of map.services) {
    const dirLabel = s.dir === '' ? './' : `${s.dir}/`
    const readme = s.hasReadme ? 'has README' : 'no README'
    lines.push(`- \`${dirLabel}\` — ${s.name} (${s.ecosystem}, ${s.sizeBucket}, ${readme})`)
  }
  if (map.truncated) {
    lines.push(`- … more packages omitted (cap ${MAX_SERVICES})`)
  }
  lines.push(
    '',
    'Use this map to orient exploration without spending turns on top-level discovery.',
    '',
  )
  return lines.join('\n')
}

// ─── Spawn-time injection ─────────────────────────────────────────────────────

interface CacheEntry { filePath: string; at: number }
const cache = new Map<string, CacheEntry>()
const CACHE_TTL_MS = 60_000

export function isRepoMapEnabled(): boolean {
  return process.env.SPECRAILS_REPO_MAP !== 'false'
}

/**
 * Build (or reuse, 60s TTL) the on-disk map for a repo/worktree. Returns the
 * file path, or null on any failure — the map is an accelerator, never a
 * spawn blocker.
 */
export function ensureRepoMapFile(repoDir: string): string | null {
  try {
    const real = fs.realpathSync(repoDir)
    const hit = cache.get(real)
    if (hit && Date.now() - hit.at < CACHE_TTL_MS && fs.existsSync(hit.filePath)) {
      return hit.filePath
    }
    const content = formatRepoMap(buildRepoMap(real))
    const dir = path.join(resolveHome(), '.specrails', 'repo-maps')
    fs.mkdirSync(dir, { recursive: true })
    const filePath = path.join(dir, `${sha1(real)}.md`)
    const tmp = `${filePath}.tmp-${process.pid}`
    fs.writeFileSync(tmp, content, 'utf8')
    fs.renameSync(tmp, filePath)
    cache.set(real, { filePath, at: Date.now() })
    return filePath
  } catch {
    return null
  }
}

/** Add `SPECRAILS_REPO_MAP_PATH` to a spawn env. Never throws, never blocks. */
export function injectRepoMapEnv(env: NodeJS.ProcessEnv, repoDir: string | undefined | null): NodeJS.ProcessEnv {
  if (!repoDir || !isRepoMapEnabled()) return env
  const filePath = ensureRepoMapFile(repoDir)
  return filePath ? { ...env, SPECRAILS_REPO_MAP_PATH: filePath } : env
}

/** Test hook — clears the TTL cache. */
export function _clearRepoMapCache(): void {
  cache.clear()
}

// ─── Internals ────────────────────────────────────────────────────────────────

function sha1(value: string): string {
  return crypto.createHash('sha1').update(value).digest('hex')
}

function listDirs(dir: string): string[] {
  let entries: fs.Dirent[]
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true })
  } catch {
    return []
  }
  return entries
    .filter((e) => e.isDirectory() && !e.name.startsWith('.') && !SKIP_DIRS.has(e.name))
    .map((e) => e.name)
    .sort()
}

function detectEcosystem(dir: string): string | null {
  for (const [manifest, eco] of MANIFESTS) {
    if (fs.existsSync(path.join(dir, manifest))) return eco
  }
  return null
}

function packageName(dir: string): string | null {
  try {
    const raw = fs.readFileSync(path.join(dir, 'package.json'), 'utf8')
    const parsed = JSON.parse(raw) as { name?: unknown }
    return typeof parsed.name === 'string' && parsed.name.trim() ? parsed.name.trim() : null
  } catch {
    return null
  }
}

function readmePath(dir: string): string | null {
  for (const name of ['README.md', 'readme.md', 'README.txt', 'README']) {
    const p = path.join(dir, name)
    if (fs.existsSync(p)) return p
  }
  return null
}

function readReadmeExcerpt(repoDir: string): string | null {
  const p = readmePath(repoDir)
  if (!p) return null
  try {
    const lines = fs.readFileSync(p, 'utf8').split('\n').slice(0, README_MAX_LINES)
    const text = lines.join('\n').trim()
    if (!text) return null
    return text.length > README_MAX_CHARS ? `${text.slice(0, README_MAX_CHARS)}…` : text
  } catch {
    return null
  }
}

/** Rough size label from a capped, shallow file count. */
function sizeBucket(dir: string): 'small' | 'medium' | 'large' {
  let count = 0
  const walk = (d: string, depth: number): void => {
    if (depth > SCAN_MAX_DEPTH || count > SCAN_MAX_ENTRIES) return
    let entries: fs.Dirent[]
    try {
      entries = fs.readdirSync(d, { withFileTypes: true })
    } catch {
      return
    }
    for (const e of entries) {
      if (count > SCAN_MAX_ENTRIES) return
      if (e.name.startsWith('.') || SKIP_DIRS.has(e.name)) continue
      if (e.isDirectory()) {
        walk(path.join(d, e.name), depth + 1)
      } else {
        count++
      }
    }
  }
  walk(dir, 0)
  if (count < 20) return 'small'
  if (count < 150) return 'medium'
  return 'large'
}

/**
 * Resolve npm/yarn `workspaces` from the root package.json. Literal paths and
 * trailing `/*` globs only — deliberately no glob library; anything fancier
 * falls back to the top-level scan.
 */
function resolveNpmWorkspaces(repoDir: string): string[] {
  let patterns: string[] = []
  try {
    const raw = fs.readFileSync(path.join(repoDir, 'package.json'), 'utf8')
    const parsed = JSON.parse(raw) as { workspaces?: unknown }
    const ws = parsed.workspaces
    if (Array.isArray(ws)) {
      patterns = ws.filter((w): w is string => typeof w === 'string')
    } else if (ws && typeof ws === 'object' && Array.isArray((ws as { packages?: unknown }).packages)) {
      patterns = ((ws as { packages: unknown[] }).packages).filter((w): w is string => typeof w === 'string')
    }
  } catch {
    return []
  }
  const out: string[] = []
  for (const pattern of patterns) {
    const clean = pattern.replace(/^\.\//, '')
    if (clean.endsWith('/*')) {
      const base = clean.slice(0, -2)
      const abs = path.join(repoDir, base)
      for (const child of listDirs(abs)) {
        out.push(path.join(base, child))
      }
    } else if (!clean.includes('*')) {
      out.push(clean)
    }
  }
  return out
}
