// Deterministic rendering + persistence of the Blueprint pair (design D5).
//
// `blueprint.json` is the source of truth; `blueprint.md` is a deterministic
// render regenerated on EVERY json write and never hand-edited. Both live in
// `<workspace>/.specrails/` — never in the project repo (pristine-repo
// invariant). Writes are temp+rename so a crash never leaves a torn file.

import fs from 'fs'
import path from 'path'
import { Blueprint, BlueprintMilestone } from './blueprint-types'
import { coerceBlueprint } from './blueprint-draft-parser'

export const BLUEPRINT_JSON = 'blueprint.json'
export const BLUEPRINT_MD = 'blueprint.md'

function renderMilestone(m: BlueprintMilestone, index: number): string {
  const lines: string[] = []
  lines.push(`### M${index + 1} — ${m.title}`)
  lines.push('')
  lines.push(`- **Status**: ${m.status}`)
  if (m.goal !== '') lines.push(`- **Goal**: ${m.goal}`)
  if (m.plannedSpecs.length > 0) {
    lines.push('- **Planned specs**:')
    for (const spec of m.plannedSpecs) lines.push(`  - ${spec}`)
  }
  return lines.join('\n')
}

/**
 * Deterministic markdown render of a blueprint: same input bytes → same
 * output bytes (no timestamps, no ordering surprises — arrays render in
 * stored order).
 */
export function renderBlueprintMarkdown(blueprint: Blueprint): string {
  const sections: string[] = []
  const name = blueprint.product.name !== '' ? blueprint.product.name : 'Untitled project'
  sections.push(`# Blueprint — ${name}`)

  const product: string[] = ['## Product', '']
  product.push(`- **Pitch**: ${blueprint.product.pitch !== '' ? blueprint.product.pitch : '_N/A_'}`)
  product.push(`- **Audience**: ${blueprint.product.audience !== '' ? blueprint.product.audience : '_N/A_'}`)
  product.push(`- **Core flow**: ${blueprint.coreFlow !== '' ? blueprint.coreFlow : '_N/A_'}`)
  product.push(`- **Platform**: ${blueprint.platform !== '' ? blueprint.platform : '_N/A_'}`)
  sections.push(product.join('\n'))

  const stack: string[] = ['## Stack', '']
  stack.push(`- **Language**: ${blueprint.stack.language !== '' ? blueprint.stack.language : '_N/A_'}`)
  stack.push(`- **Framework**: ${blueprint.stack.framework !== '' ? blueprint.stack.framework : '_N/A_'}`)
  stack.push(`- **Database**: ${blueprint.stack.db !== '' ? blueprint.stack.db : '_N/A_'}`)
  if (blueprint.stack.notes) stack.push(`- **Notes**: ${blueprint.stack.notes}`)
  sections.push(stack.join('\n'))

  if (blueprint.assumptions.length > 0) {
    sections.push(['## Assumptions', '', ...blueprint.assumptions.map((a) => `- ${a}`)].join('\n'))
  }

  if (blueprint.milestones.length > 0) {
    sections.push(['## Milestones', '', blueprint.milestones.map(renderMilestone).join('\n\n')].join('\n'))
  }

  if (blueprint.m1Specs.length > 0) {
    const specs: string[] = ['## Milestone 1 specs', '']
    blueprint.m1Specs.forEach((spec, i) => {
      specs.push(`${i + 1}. **${spec.title}**${spec.labels.length > 0 ? ` (${spec.labels.join(', ')})` : ''}`)
    })
    sections.push(specs.join('\n'))
  }

  sections.push('---\n\n_Generated by Specrails Project Builder. Do not edit — regenerated from `blueprint.json`._')
  return sections.join('\n\n') + '\n'
}

function writeAtomic(filePath: string, content: string): void {
  const tmp = `${filePath}.tmp`
  fs.writeFileSync(tmp, content, 'utf-8')
  fs.renameSync(tmp, filePath)
}

/** Resolve the blueprint.json path inside a workspace. */
export function blueprintJsonPath(workspaceDir: string): string {
  return path.join(workspaceDir, '.specrails', BLUEPRINT_JSON)
}

/**
 * Write the blueprint pair (json + regenerated md) into
 * `<workspaceDir>/.specrails/`. Atomic per file (temp+rename).
 */
export function writeBlueprintPair(workspaceDir: string, blueprint: Blueprint): void {
  const dir = path.join(workspaceDir, '.specrails')
  fs.mkdirSync(dir, { recursive: true })
  writeAtomic(path.join(dir, BLUEPRINT_JSON), JSON.stringify(blueprint, null, 2) + '\n')
  writeAtomic(path.join(dir, BLUEPRINT_MD), renderBlueprintMarkdown(blueprint))
}

/**
 * Read a workspace's blueprint.json. Returns null when absent or unreadable
 * (a torn/corrupt file must never crash a route).
 */
export function readBlueprint(workspaceDir: string): Blueprint | null {
  try {
    const raw = fs.readFileSync(blueprintJsonPath(workspaceDir), 'utf-8')
    return coerceBlueprint(JSON.parse(raw))
  } catch {
    return null
  }
}
